#! /usr/bin/python3

import ffmpeg
import sys

args = sys.argv

if len(args) == 3:
    video = args[1]
    ss = 0
    to = args[2]
elif len(args) == 4:
    video = args[1]
    ss = args[2]
    to = args[3]
else:
    exit()
output = video.split(".")[0] + "_clipped." + video.split(".")[1]
ffmpeg.input(video) \
.output(output, ss=ss, to=to, vcodec='h264_nvenc', acodec='copy').run(overwrite_output=True)
