#! /usr/bin/python3

import ffmpeg
import glob
import sys

args = sys.argv

if len(args) == 2:
    video = args[1]
else:
    videos = glob.glob("*.mp4")
    videos.sort()
    video = videos[0]
ffmpeg.input(video) \
.output("short.mp4", vf='pad=w=iw:h=ih+2333:x=0:y=1166:color=black', acodec='copy', s='1080x1920').run()
