#! /usr/bin/python3

import ffmpeg
import glob
import sys

args = sys.argv

if len(args) == 2:
    video = args[1]
else:
    videos = glob.glob("*.mp4")
    videos.sort()
    video = videos[0]
output = video.split(".")[0] + "_short." + video.split(".")[1]
ffmpeg.input(video) \
.output(output, t='59.9', vf='pad=w=iw:h=ih+2333:x=0:y=1166:color=black,setpts=PTS/1.3', af='atempo=1.3', vcodec='h264_nvenc', s='1080x1920').run()
